"""Verify ADRC evidence gates and atomic publication entirely in an in-memory filesystem.

Synthetic successful reports exist only inside mocks. These tests never launch MATLAB,
write generated controller files, publish a real Keil target, or delete filesystem paths.
"""
from __future__ import annotations

from contextlib import ExitStack
import hashlib
import json
import os
from pathlib import Path
import types
import unittest
from unittest.mock import patch
import xml.etree.ElementTree as ET


PROJECT_ROOT = Path(__file__).resolve().parents[2]
TARGET_SCRIPT = PROJECT_ROOT / "tools/prepare_adrc_target.py"
TARGET_GATE = types.ModuleType("adrc_target_gate_under_test")
TARGET_GATE.__file__ = str(TARGET_SCRIPT)
exec(compile(TARGET_SCRIPT.read_text(encoding="utf-8"), str(TARGET_SCRIPT), "exec"), TARGET_GATE.__dict__)


class MemoryProject:
    """Model verified inputs, previous publication and write failures without touching the real project."""

    def __init__(self) -> None:
        """Build minimal evidence and Keil XML fixtures under a virtual test-only project root."""
        self.project = PROJECT_ROOT / "output/adrc/test_fixtures/memory_project"
        self.run = self.project / "output/adrc/models/verified-run"
        self.generated = self.run / "generated"
        self.baseline = self.project / "MDK-ARM/CtrBoard-H7_FDCAN.uvprojx"
        self.target = self.project / "MDK-ARM/ADRC-Bench.uvprojx"
        self.old_snapshot = self.project / "App/Adrc/Generated/previous/adrc_controller.c"
        self.files_motor_path = self.project / "App/Motor/motor_adrc_command.c"
        self.report_path = self.run / "pipeline_report.json"
        self.files: dict[Path, bytes] = {}
        self.files[self.files_motor_path] = b"integration:motor_adrc_command.c"
        self.events: list[tuple[str, Path]] = []
        self.directories: set[Path] = set()
        self.copy_failure = False
        self.replace_failure = False
        self.after_copy = None
        self.files[self.baseline] = b"""<Project><Targets><Target><TargetName>LCD-ReadOnly</TargetName>
        <TargetOption><TargetCommonOption><OutputDirectory>old/</OutputDirectory><OutputName>old</OutputName>
        <ListingPath>old/</ListingPath></TargetCommonOption><TargetArmAds><Cads><VariousControls>
        <Define>STM32H723xx,AETHOR_S3519_SAME_MODEL_MASK=0x7F</Define><IncludePath>../App</IncludePath>
        </VariousControls></Cads></TargetArmAds></TargetOption><Groups/></Target>
        <Target><TargetName>Unrelated-Original-Target</TargetName></Target></Targets>
        <RTE><targetInfos><targetInfo name="LCD-ReadOnly"/></targetInfos></RTE></Project>"""
        self.files[self.target] = b"previous usable target refers to Generated/previous"
        self.files[self.old_snapshot] = b"previous immutable generated bytes"
        for name in ("adrc_experiment.c", "adrc_protocol.c", "adrc_bench.c",
                     "adrc_app_bridge.c", "adrc_generated_adapter.c"):
            self.files[self.project / "App/Adrc" / name] = ("integration:" + name).encode()
        self.files[self.project / "App/Platform/stm32_adrc_channel.c"] = b"platform input"
        self.sources = [self.project / "Models/Adrc" / name for name in (
            "run_adrc_pipeline.m", "build_adrc_models.m", "adrc_simulation_parameters.m", "adrc_generated_replay.c")]
        self.models = [self.run / name for name in (
            "adrc_controller.slx", "adrc_plant.slx", "adrc_validation.slx")]
        self.generated_files = [self.generated / name for name in (
            "adrc_controller.c", "adrc_controller.h", "rtwtypes.h", "ert_main.c")]
        for path in self.sources + self.models + self.generated_files:
            self.files[path] = ("in-memory unittest fixture only:" + path.name).encode()
        self.report = {
            "passed": True, "stage": "completed", "verificationHashesMatch": True,
            "controllerMil": {"passed": True}, "closedLoopMil": {"passed": True}, "cReplay": {"passed": True},
            "generatedBuild": {"BuildDirectory": str(self.generated)},
            "models": {path.stem: str(path) for path in self.models},
            "verificationArtifacts": self.manifest(self.models + self.generated_files),
            "verificationSources": self.manifest(self.sources),
        }
        self.save_report()

    def manifest(self, paths: list[Path]) -> list[dict[str, str]]:
        """Return deterministic test-only digests for the specified in-memory bytes."""
        return [{"path": str(path), "sha256": hashlib.sha256(self.files[path]).hexdigest()} for path in paths]

    def save_report(self) -> None:
        """Update synthetic report bytes in memory without recording a production write event."""
        self.files[self.report_path] = json.dumps(self.report, sort_keys=True).encode()

    @staticmethod
    def canonical(path: Path) -> Path:
        """Normalize lexical dot segments while avoiding real filesystem resolution."""
        return Path(os.path.abspath(os.path.normpath(str(path))))

    def exists(self, path: Path) -> bool:
        """Recognize virtual files and their ancestors as existing filesystem nodes."""
        path = self.canonical(path)
        return path in self.files or path in self.directories or any(path in item.parents for item in self.files)

    def resolve(self, path: Path, strict: bool = False) -> Path:
        """Honor strict missing-path failures in the evidence validator."""
        resolved = self.canonical(path)
        if strict and not self.exists(resolved):
            raise FileNotFoundError(str(resolved))
        return resolved

    def read_bytes(self, path: Path) -> bytes:
        """Read virtual content or raise the same missing-file error as pathlib."""
        try:
            return self.files[self.canonical(path)]
        except KeyError as error:
            raise FileNotFoundError(str(path)) from error

    def write_bytes(self, path: Path, content: bytes) -> int:
        """Record a virtual write so tests can verify the exact publication order."""
        path = self.canonical(path)
        self.events.append(("write", path))
        self.files[path] = bytes(content)
        return len(content)

    def mkdir(self, path: Path, **_kwargs) -> None:
        """Create only a virtual directory and retain the write-side-effect trace."""
        path = self.canonical(path)
        self.events.append(("mkdir", path))
        self.directories.add(path)

    def copyfile(self, source: Path, destination: Path) -> None:
        """Simulate a successful copy or an injected storage error before atomic publication."""
        self.events.append(("copy", self.canonical(destination)))
        if self.copy_failure:
            raise OSError("injected copy failure")
        self.files[self.canonical(destination)] = self.read_bytes(source)
        if self.after_copy is not None:
            self.after_copy(source, destination)

    def replace(self, source: Path, destination: Path) -> None:
        """Model the final atomic replacement without deleting or modifying any real path."""
        self.events.append(("replace", self.canonical(destination)))
        if self.replace_failure:
            raise OSError("injected atomic publication failure")
        self.files[self.canonical(destination)] = self.files.pop(self.canonical(source))

    def patches(self) -> ExitStack:
        """Intercept every read/write operation used by the publisher while retaining its actual logic."""
        stack = ExitStack()
        stack.enter_context(patch.object(Path, "resolve", lambda path, strict=False: self.resolve(path, strict)))
        stack.enter_context(patch.object(Path, "is_file", lambda path: self.canonical(path) in self.files))
        stack.enter_context(patch.object(Path, "exists", lambda path: self.exists(path)))
        stack.enter_context(patch.object(Path, "iterdir", lambda path: iter(
            item for item in list(self.files) if item.parent == self.canonical(path))))
        stack.enter_context(patch.object(Path, "read_bytes", lambda path: self.read_bytes(path)))
        stack.enter_context(patch.object(Path, "read_text", lambda path, encoding="utf-8": self.read_bytes(path).decode(encoding)))
        stack.enter_context(patch.object(Path, "mkdir", lambda path, **kwargs: self.mkdir(path, **kwargs)))
        stack.enter_context(patch.object(Path, "write_bytes", lambda path, content: self.write_bytes(path, content)))
        stack.enter_context(patch.object(Path, "write_text", lambda path, text, encoding="utf-8": self.write_bytes(path, text.encode(encoding))))
        stack.enter_context(patch.object(TARGET_GATE.shutil, "copyfile", self.copyfile))
        stack.enter_context(patch.object(TARGET_GATE.os, "replace", self.replace))
        stack.enter_context(patch.object(TARGET_GATE.ET, "parse", lambda path: ET.ElementTree(ET.fromstring(self.read_bytes(path)))))
        return stack


class TargetGateTests(unittest.TestCase):
    """Exercise the real publisher's evidence checks and failure ordering against virtual storage."""

    def setUp(self) -> None:
        """Start every test with fresh evidence and a previously usable target/snapshot pair."""
        self.storage = MemoryProject()
        self.old_target_bytes = self.storage.files[self.storage.target]
        self.old_snapshot_bytes = self.storage.files[self.storage.old_snapshot]
        self.baseline_bytes = self.storage.files[self.storage.baseline]

    def assert_old_publication_unchanged(self) -> None:
        """Check that neither old publication nor the original multi-target Keil project was modified."""
        self.assertEqual(self.storage.files[self.storage.target], self.old_target_bytes)
        self.assertEqual(self.storage.files[self.storage.old_snapshot], self.old_snapshot_bytes)
        self.assertEqual(self.storage.files[self.storage.baseline], self.baseline_bytes)

    def assert_rejected_before_writes(self) -> None:
        """Require all malformed evidence to fail before copies, directories, manifests or publication."""
        with self.storage.patches(), self.assertRaises((ValueError, FileNotFoundError)):
            TARGET_GATE.prepare_target(self.storage.project, self.storage.run)
        self.assertEqual(self.storage.events, [])
        self.assert_old_publication_unchanged()

    def test_missing_verification_hashes(self) -> None:
        """Old passed reports without verification-time artifact hashes cannot publish a target."""
        self.storage.report.pop("verificationArtifacts")
        self.storage.save_report()
        self.assert_rejected_before_writes()

    def test_generated_code_modified_after_verification(self) -> None:
        """A passed report cannot certify later changed generated C bytes."""
        self.storage.files[self.storage.generated_files[0]] += b" changed after replay"
        self.assert_rejected_before_writes()

    def test_missing_model(self) -> None:
        """A missing SLX fails before any new snapshot copy or target write."""
        self.storage.files.pop(self.storage.models[1])
        self.assert_rejected_before_writes()

    def test_model_source_modified_after_verification(self) -> None:
        """Changed maintained model source invalidates the verification source manifest."""
        self.storage.files[self.storage.sources[0]] += b" changed model source"
        self.assert_rejected_before_writes()

    def test_missing_source_manifest_member(self) -> None:
        """Source evidence must cover the exact four maintained model inputs."""
        self.storage.report["verificationSources"].pop()
        self.storage.save_report()
        self.assert_rejected_before_writes()

    def test_unhashed_generated_header(self) -> None:
        """An extra generated header cannot evade the artifact manifest's closure check."""
        self.storage.files[self.storage.generated / "unverified_extra.h"] = b"not included in verified manifest"
        self.assert_rejected_before_writes()

    def test_artifact_outside_verified_run(self) -> None:
        """A correct digest alone cannot admit a path outside the isolated model run."""
        outside = self.storage.project / "outside.slx"
        self.storage.files[outside] = b"outside allowed run"
        self.storage.report["verificationArtifacts"] += self.storage.manifest([outside])
        self.storage.save_report()
        self.assert_rejected_before_writes()

    def test_missing_integration_source(self) -> None:
        """All handwritten integration dependencies are checked before generated snapshots are copied."""
        self.storage.files.pop(self.storage.project / "App/Adrc/adrc_generated_adapter.c")
        self.assert_rejected_before_writes()

    def test_success_publishes_immutable_snapshot_atomically(self) -> None:
        """Only fully bound evidence publishes one target with unchanged baseline and truthful hardware flags."""
        report_digest = hashlib.sha256(self.storage.files[self.storage.report_path]).hexdigest()
        snapshot = self.storage.project / "App/Adrc/Generated" / report_digest
        with self.storage.patches():
            result = TARGET_GATE.prepare_target(self.storage.project, self.storage.run)
        self.assertEqual(result, self.storage.target)
        self.assertEqual(self.storage.events[-1], ("replace", self.storage.target))
        self.assertEqual(self.storage.files[self.storage.baseline], self.baseline_bytes)
        self.assertEqual(self.storage.files[self.storage.old_snapshot], self.old_snapshot_bytes)
        target = ET.fromstring(self.storage.files[result])
        self.assertEqual([item.text for item in target.findall("Targets/Target/TargetName")], ["ADRC-Bench"])
        include_path = target.findtext("Targets/Target/TargetOption/TargetArmAds/Cads/VariousControls/IncludePath")
        self.assertIn(report_digest, include_path)
        manifest = json.loads(self.storage.files[snapshot / "generation-manifest.json"])
        self.assertFalse(manifest["hardware_qualified"])
        self.assertFalse(manifest["hardware_tested"])
        self.assertEqual(manifest["pipeline_report_sha256"], report_digest)
        self.assertEqual(manifest["project_sha256"], hashlib.sha256(self.storage.files[result]).hexdigest())
        self.assertNotIn(snapshot / "ert_main.c", self.storage.files)
        for record in manifest["generated_files"]:
            self.assertEqual(hashlib.sha256(self.storage.files[snapshot / record["name"]]).hexdigest(), record["sha256"])

    def test_copy_failure_preserves_old_publication(self) -> None:
        """A snapshot copy error cannot replace the previous target or its immutable generated code."""
        self.storage.copy_failure = True
        with self.storage.patches(), self.assertRaises(OSError):
            TARGET_GATE.prepare_target(self.storage.project, self.storage.run)
        self.assertFalse(any(event == "replace" for event, _path in self.storage.events))
        self.assert_old_publication_unchanged()

    def test_changed_evidence_during_copy_prevents_publication(self) -> None:
        """The second evidence check catches a generated file changed after initial validation."""
        def change_verified_model(_source: Path, _destination: Path) -> None:
            """Inject a concurrent edit only into virtual model bytes after a snapshot copy."""
            self.storage.files[self.storage.models[0]] += b" changed during copy"
        self.storage.after_copy = change_verified_model
        with self.storage.patches(), self.assertRaises(ValueError):
            TARGET_GATE.prepare_target(self.storage.project, self.storage.run)
        self.assertFalse(any(event == "replace" for event, _path in self.storage.events))
        self.assert_old_publication_unchanged()

    def test_atomic_replace_failure_preserves_old_publication(self) -> None:
        """A final publication failure leaves the old project and old snapshot usable."""
        self.storage.replace_failure = True
        with self.storage.patches(), self.assertRaises(OSError):
            TARGET_GATE.prepare_target(self.storage.project, self.storage.run)
        self.assertEqual(self.storage.events[-1], ("replace", self.storage.target))
        self.assert_old_publication_unchanged()

    def test_conflicting_existing_snapshot_is_not_overwritten(self) -> None:
        """A preexisting snapshot with conflicting bytes fails without silently repairing published content."""
        digest = hashlib.sha256(self.storage.files[self.storage.report_path]).hexdigest()
        conflict = self.storage.project / "App/Adrc/Generated" / digest / "adrc_controller.c"
        self.storage.files[conflict] = b"existing immutable conflicting content"
        with self.storage.patches(), self.assertRaises(ValueError):
            TARGET_GATE.prepare_target(self.storage.project, self.storage.run)
        self.assertEqual(self.storage.files[conflict], b"existing immutable conflicting content")
        self.assertFalse(any(event == "replace" for event, _path in self.storage.events))
        self.assert_old_publication_unchanged()


if __name__ == "__main__":
    unittest.main(verbosity=2)
