"""Generate an OFL-licensed 16px LVGL bitmap subset from pinned Noto CJK Sans.

The source font lives in the authorized output/deps directory. No system font
or raster screenshot is used. Every literal UI codepoint is recorded for QA.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import struct
from PIL import Image, ImageDraw, ImageFont


def font_copyright(font_path: Path) -> list[str]:
    """Read exact copyright records from the redistributable OTF name table."""
    data = font_path.read_bytes()
    table_count = struct.unpack_from(">H", data, 4)[0]
    for table_index in range(table_count):
        tag, _, offset, _ = struct.unpack_from(">4sIII", data, 12 + table_index * 16)
        if tag != b"name":
            continue
        _, count, strings_offset = struct.unpack_from(">HHH", data, offset)
        values = set()
        for index in range(count):
            platform, _, _, name_id, length, start = struct.unpack_from(">HHHHHH", data, offset + 6 + index * 12)
            if name_id == 0:
                raw = data[offset + strings_offset + start:offset + strings_offset + start + length]
                values.add(raw.decode("utf-16-be" if platform in (0, 3) else "mac_roman"))
        return sorted(values)
    raise ValueError("Missing font copyright table")


def generate(font_path: Path, license_path: Path) -> None:
    """Rasterize sparse Unicode glyphs into LVGL's uncompressed 4-bit format."""
    root = Path(__file__).resolve().parents[2]
    output = root / "Ui/fonts"
    output.mkdir(parents=True, exist_ok=True)
    codepoints = set(range(32, 127)) | {0xB0}
    for source in (root / "Ui/debug_ui_view.c", root / "App/DebugUi/debug_ui_model.c"):
        for literal in re.findall(r'"(?:\\.|[^"\\])*"', source.read_text(encoding="utf-8")):
            codepoints.update(ord(character) for character in literal if ord(character) > 127)
    font = ImageFont.truetype(str(font_path), 16)
    bitmap = []
    descriptors = ["    {0, 0, 0, 0, 0, 0}, /* reserved glyph 0 */"]
    for codepoint in sorted(codepoints):
        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width, height = right - left, bottom - top
        bitmap_start = len(bitmap)
        if width and height:
            raster = Image.new("L", (width, height), 0)
            ImageDraw.Draw(raster).text((-left, -top), character, font=font, fill=255, anchor="ls")
            pixels = [int(value) * 15 // 255 for value in raster.get_flattened_data()]
            if len(pixels) % 2:
                pixels.append(0)
            bitmap.extend((pixels[index] << 4) | pixels[index + 1] for index in range(0, len(pixels), 2))
        descriptors.append(
            f"    {{{bitmap_start}, {round(font.getlength(character) * 16)}, {width}, {height}, {left}, {-bottom}}}, /* U+{codepoint:04X} */"
        )
    ordered = sorted(codepoints)
    lines = [
        "/** @file ui_font_16.c",
        " * @brief Generated 16px Noto CJK Sans subset; SIL OFL 1.1, see OFL.txt.",
        " * Generated by Tests/ui/generate_font_subset.py; no commercial system fonts.",
        " */",
        '#include "lvgl.h"',
        "static const uint8_t glyph_bitmap[] = {",
    ]
    lines.extend("    " + ", ".join(f"0x{value:02x}" for value in bitmap[index:index + 20]) + "," for index in range(0, len(bitmap), 20))
    lines.extend(["};", "/** @brief Sparse glyph metrics: bitmap offset, 1/16px advance and baseline box. */", "static const lv_font_fmt_txt_glyph_dsc_t glyph_descriptors[] = {"])
    lines.extend(descriptors)
    lines.extend(["};", "static const uint16_t unicode_offsets[] = {"])
    lines.extend("    " + ", ".join(str(value - 32) for value in ordered[index:index + 16]) + "," for index in range(0, len(ordered), 16))
    lines.extend([
        "};",
        "/** @brief Sparse cmap covers the exact versioned UI character inventory. */",
        "static const lv_font_fmt_txt_cmap_t cmaps[] = {{",
        f"    .range_start = 32, .range_length = {ordered[-1] - 31}, .glyph_id_start = 1,",
        f"    .unicode_list = unicode_offsets, .glyph_id_ofs_list = NULL, .list_length = {len(ordered)},",
        "    .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY",
        "}};",
        "static lv_font_fmt_txt_glyph_cache_t glyph_cache;",
        "/** @brief Immutable glyph data with a UiTask-owned one-entry lookup cache. */",
        "static const lv_font_fmt_txt_dsc_t font_description = {",
        "    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_descriptors, .cmaps = cmaps,",
        "    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1, .bpp = 4,",
        "    .kern_classes = 0, .bitmap_format = 0, .cache = &glyph_cache",
        "};",
        "/** @brief Public LVGL v8 font, renamed as required for this derived subset. */",
        "const lv_font_t ui_font_16 = {",
        "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,",
        "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
        "    .line_height = 20, .base_line = 4, .subpx = LV_FONT_SUBPX_NONE,",
        "    .underline_position = -2, .underline_thickness = 1, .dsc = &font_description,",
        "    .fallback = NULL, .user_data = NULL",
        "};",
    ])
    (output / "ui_font_16.c").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (output / "charset.txt").write_text("".join(chr(value) for value in ordered) + "\n", encoding="utf-8")
    (output / "OFL.txt").write_bytes(license_path.read_bytes())
    metadata = {
        "font": "NotoSansCJKsc-Regular.otf",
        "tag": "Sans2.004",
        "source": "https://raw.githubusercontent.com/notofonts/noto-cjk/Sans2.004/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf",
        "source_sha256": hashlib.sha256(font_path.read_bytes()).hexdigest(),
        "copyright": font_copyright(font_path),
        "license": "SIL Open Font License 1.1 (OFL.txt)",
        "generator": "Tests/ui/generate_font_subset.py (Pillow/FreeType)",
        "glyphs": len(ordered), "bitmap_bytes": len(bitmap), "size_px": 16, "bpp": 4,
    }
    (output / "SOURCE.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metadata))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", type=Path)
    parser.add_argument("license", type=Path)
    arguments = parser.parse_args()
    generate(arguments.font, arguments.license)
