/**
 * @file aethor_app.h
 * @brief Defines the Phase 0 application lifecycle and read-only snapshots.
 */

#ifndef APP_AETHOR_APP_H
#define APP_AETHOR_APP_H

#include <stdbool.h>
#include <stdint.h>

#include "arm_controller.h"
#include "can_tx_scheduler.h"
#include "diagnostics.h"
#include "motor_runtime.h"
#include "protocol_engine.h"
#include "DebugUi/debug_ui_contract.h"
#include "Config/adrc_build_config.h"
#if AETHOR_ADRC_BENCH || AETHOR_ADRC_LCD_INTEGRATED
#include "Adrc/adrc_experiment.h"
/** @brief Pops the single current ADRC frame; kind is enable=0, nominal torque=1, disable=2. */
uint8_t aethor_app_adrc_pop_frame(CanFrame *frame, uint8_t *kind, float *decoded_torque_nm);
/** @brief Reports actual CAN transmission, never queue admission or measured physical torque. */
void aethor_app_adrc_report_transmit(uint8_t kind, float decoded_torque_nm, uint8_t succeeded);
#if AETHOR_ADRC_LCD_INTEGRATED
/** @brief Records a real transmission timestamp for the measured LCD handback gate. */
void aethor_app_adrc_report_transmit_at(uint8_t kind, float decoded_torque_nm,
    uint8_t succeeded, uint64_t timestamp_us);
/** @brief Publishes one timestamped legacy scheduler and hardware FIFO drain sample. */
void aethor_app_integrated_set_can_idle(uint8_t idle, uint64_t timestamp_us);
/** @brief Resets the handoff quiet window after any legacy CAN submission attempt. */
void aethor_app_integrated_note_legacy_can_activity(void);
/** @brief Emits one read-only motor-7 feedback probe while acquisition owns the handoff gate. */
uint8_t aethor_app_integrated_pop_probe_frame(CanFrame *frame, uint64_t timestamp_us);
/** @brief Records the dedicated CAN probe transmission result, never motor execution. */
void aethor_app_integrated_report_probe_transmit(uint8_t succeeded, uint64_t timestamp_us);
#endif
/** @brief Supplies local measured hardware evidence; no USB path calls this hook. */
AdrcExperimentResult aethor_app_adrc_set_evidence(const AdrcExperimentConfig *config,
    const AdrcExperimentQualification *qualification, uint64_t timestamp_us);
/** @brief Copies coherent supervisor status under the same task critical boundary. */
uint8_t aethor_app_adrc_get_status(AdrcExperimentStatus *status);
#endif

/** @brief ProtocolTask-only bounded local STOP/admission and health service pass. */
void aethor_app_debug_ui_process(uint64_t timestamp_us);
/** @brief UiTask reserves a mailbox request; success does not mean motion admitted. */
DebugUiReason aethor_app_debug_ui_submit(const DebugUiRequest *request);
/** @brief Copies a coherent UI snapshot under the existing task critical hooks. */
bool aethor_app_debug_ui_get_snapshot(uint64_t timestamp_us, DebugUiSnapshot *snapshot);
/** @brief UiTask consumes one admission acknowledgement, matched by complete identity. */
bool aethor_app_debug_ui_poll_admission(DebugUiAdmission *admission);
/** @brief UiTask consumes one terminal acknowledgement, matched by complete identity. */
bool aethor_app_debug_ui_poll_completion(DebugUiCompletion *completion);
/** @brief UiTask publishes input/display-checked progress; does not refresh USB watchdog. */
void aethor_app_debug_ui_update_health(const DebugUiHealth *health);
/** @brief Indicates local request/STOP/health work for a ProtocolTask notification. */
bool aethor_app_debug_ui_needs_service(void);
/** @brief Injects one explicit evidence profile while REMOTE and idle; defaults are invalid. */
bool aethor_app_debug_ui_set_motor_profile(uint8_t motor_id, const DebugUiMotorProfile *profile);
/** @brief Copies the exact current evidence profile; ID is one-based 1..7. */
bool aethor_app_debug_ui_get_motor_profile(uint8_t motor_id, DebugUiMotorProfile *profile);

/** @brief Enters or exits one platform task-scheduling critical boundary. */
typedef void (*AethorAppTaskCriticalHook)(void);

/**
 * @brief Installs paired task-critical hooks for cross-task query snapshots.
 * @param enter_hook Platform hook called before bounded shared-state reads.
 * @param exit_hook Platform hook called after the matching context publish.
 * @note Passing either hook as NULL disables both hooks for host execution.
 */
void aethor_app_set_task_critical_hooks(
    AethorAppTaskCriticalHook enter_hook,
    AethorAppTaskCriticalHook exit_hook);

/**
 * @brief Initializes all static Phase 0 application state.
 * @param timestamp_us Initialization timestamp in microseconds.
 * @param boot_id Nonzero boot identity generated by the STM32 entry point.
 */
void aethor_app_init(uint64_t timestamp_us, uint32_t boot_id);

/**
 * @brief Executes one non-blocking Phase 0 application service cycle.
 * @param timestamp_us Current monotonic time in microseconds.
 */
uint8_t aethor_app_service(uint64_t timestamp_us);

/**
 * @brief Produces the next bounded CAN service frame for the platform scheduler.
 * @param timestamp_us Current monotonic time in microseconds.
 * @param frame Destination frame.
 * @param priority Destination scheduler priority.
 * @return FRAME_READY, WAITING, DISCOVERY_COMPLETE, or an error.
 */
MotorRuntimeStatus aethor_app_next_can_frame(uint64_t timestamp_us,
                                             CanFrame *frame,
                                             CanTxPriority *priority);

/**
 * @brief Routes one received CAN frame through discovery or feedback decode.
 * @param frame Frame copied from the platform RX inbox.
 * @param timestamp_us Receive timestamp in microseconds.
 * @return Detailed motor runtime result.
 */
MotorRuntimeStatus aethor_app_receive_can_frame(const CanFrame *frame,
                                                uint64_t timestamp_us);

/**
 * @brief Copies the current coherent seven-motor feedback snapshot.
 * @param timestamp_us Snapshot publication timestamp.
 * @param snapshot Destination snapshot.
 * @return true after initialization when snapshot is non-null.
 */
bool aethor_app_get_motor_snapshot(uint64_t timestamp_us,
                                  MotorFeedbackSnapshot *snapshot);

/**
 * @brief Processes one complete USB protocol line in task context.
 * @param line Complete aethor-text-v1 request line without an application CRC.
 * @param length Exact line length.
 * @param timestamp_us Current monotonic timestamp.
 * @param output_batch Destination immediate response batch.
 * @return Detailed protocol lifecycle result.
 */
ProtocolEngineStatus aethor_app_process_protocol_line(
    const char *line,
    size_t length,
    uint64_t timestamp_us,
    ProtocolOutputBatch *output_batch);

/**
 * @brief Pops one pending fail-safe motor disable frame.
 * @param frame Destination emergency CAN frame.
 * @return One when copied, otherwise zero.
 */
uint8_t aethor_app_pop_emergency_can_frame(CanFrame *frame);

/**
 * @brief Pops one ordered atomic J1-J7 motion control group.
 * @param frames Destination array with capacity for ARM_JOINT_COUNT frames.
 * @return One when a complete group was copied, otherwise zero.
 */
uint8_t aethor_app_pop_control_group(
    CanFrame frames[ARM_JOINT_COUNT]);

/**
 * @brief Latches an atomic control-group scheduler rejection and stops safely.
 * @param scheduler_status Rejected scheduler status retained as fault detail.
 * @param timestamp_us Failure timestamp.
 * @return One when a terminal command result was queued, otherwise zero.
 */
uint8_t aethor_app_report_control_group_failure(
    CanTxSchedulerStatus scheduler_status,
    uint64_t timestamp_us);

/**
 * @brief Formats one pending terminal command result for ProtocolTask.
 * @param output_batch Destination output batch.
 * @return One when a result was available, otherwise zero.
 */
uint8_t aethor_app_pop_protocol_result_output(
    ProtocolOutputBatch *output_batch);

/**
 * @brief Generates due session telemetry and state-change events.
 * @param timestamp_us Current monotonic timestamp.
 * @param output_batch Destination stream output batch.
 * @return Number of generated outputs.
 */
uint8_t aethor_app_generate_stream_output(
    uint64_t timestamp_us,
    ProtocolOutputBatch *output_batch);

/**
 * @brief Formats a high-priority error for one discarded overlong USB line.
 * @param output_batch Destination output batch.
 * @return Detailed formatting status.
 */
ProtocolEngineStatus aethor_app_format_line_too_long(
    ProtocolOutputBatch *output_batch);

/**
 * @brief Copies the current arm state snapshot.
 * @param snapshot Output snapshot.
 * @return true after initialization when snapshot is non-null.
 */
bool aethor_app_get_snapshot(ArmSnapshot *snapshot);

/**
 * @brief Copies one retained diagnostic event.
 * @param logical_index Zero-based index from the oldest retained event.
 * @param event Output event copy.
 * @return true when initialized and the requested event exists.
 */
bool aethor_app_get_diagnostic(uint16_t logical_index,
                               DiagnosticEvent *event);

/**
 * @brief Copies the current diagnostic counters.
 * @param counters Output counter snapshot.
 * @return true after initialization when counters is non-null.
 */
bool aethor_app_get_diagnostic_counters(DiagnosticCounters *counters);

/**
 * @brief Applies one platform-neutral transport/resource diagnostic sample.
 * @param sample Coherent sample assembled by DiagnosticsTask.
 */
void aethor_app_update_runtime_diagnostics(
    const RuntimeDiagnosticSample *sample);

/**
 * @brief Publishes a severe transport fault to the ArmControlTask SPSC mailbox.
 * @param detail Stable platform-specific fault detail bits.
 * @param timestamp_us Fault timestamp.
 * @return One when published or an earlier global fault remains pending.
 */
uint8_t aethor_app_report_transport_fault(uint32_t detail,
                                          uint64_t timestamp_us);

#endif
