<#
.SYNOPSIS
Run the offline Simulink pipeline through MATLAB -r and record every exit status.
.DESCRIPTION
Creates a unique output directory, a job script and separate execution evidence.
This startup path has succeeded and failed on this installation; it is not a crash workaround.
No serial ports, CAN adapters, debuggers or firmware download commands are used.
#>
[CmdletBinding()]
param(
    [string]$MatlabPath = 'D:\application\MATLAB\R2026a\bin\matlab.exe',
    [string]$StartupDirectory = '',
    [ValidateRange(60, 3600)][int]$TimeoutSeconds = 1200
)
$ErrorActionPreference = 'Stop'

function ConvertTo-MatlabLiteral {
    <# Quote one path as a MATLAB character vector, including literal apostrophes. #>
    param([string]$Value)
    return "'" + $Value.Replace('\', '/').Replace("'", "''") + "'"
}

function Invoke-AdrcMatlabPipeline {
    <# Start one hidden MATLAB process and require both a successful job and exit status. #>
    $projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
    $modelDirectory = Join-Path $projectRoot 'Models\Adrc'
    if ([string]::IsNullOrEmpty($StartupDirectory)) { $StartupDirectory = $projectRoot }
    $resolvedStartupDirectory = (Resolve-Path -LiteralPath $StartupDirectory).Path
    if (-not (Test-Path -LiteralPath $MatlabPath -PathType Leaf)) {
        throw "MATLAB executable not found: $MatlabPath"
    }
    if (-not (Test-Path -LiteralPath (Join-Path $modelDirectory 'run_adrc_pipeline.m'))) {
        throw 'The ADRC MATLAB pipeline entry point is missing.'
    }
    $runDirectory = Join-Path $projectRoot ('output\adrc\models\' + [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffZ'))
    [void](New-Item -ItemType Directory -Path $runDirectory -Force)
    $jobPath = Join-Path $runDirectory 'run_job.m'
    $statusPath = Join-Path $runDirectory 'job_status.json'
    $logPath = Join-Path $runDirectory 'matlab.log'
    $modelLiteral = ConvertTo-MatlabLiteral $modelDirectory
    $outputLiteral = ConvertTo-MatlabLiteral $runDirectory
    $statusLiteral = ConvertTo-MatlabLiteral $statusPath
    $jobText = @"
% RUN_JOB Offline ADRC pipeline launcher generated by run_adrc_matlab.ps1.
% Only this isolated process exits; no existing MATLAB session is modified.
jobStatus = struct('completed', false, 'success', false, 'error', '');
try
    addpath($modelLiteral);
    run_adrc_pipeline($outputLiteral);
    jobStatus.success = true;
catch jobError
    jobStatus.error = getReport(jobError, 'extended', 'hyperlinks', 'off');
    disp(jobStatus.error);
end
jobStatus.completed = true;
statusHandle = fopen($statusLiteral, 'w', 'n', 'UTF-8');
assert(statusHandle >= 0, 'Cannot persist job status.');
fprintf(statusHandle, '%s', jsonencode(jobStatus));
fclose(statusHandle);
if jobStatus.success, exit(0); else, exit(1); end
"@
    [IO.File]::WriteAllText($jobPath, $jobText, [Text.UTF8Encoding]::new($false))
    $entryStatement = 'run(' + (ConvertTo-MatlabLiteral $jobPath) + ');'
    $arguments = @('-wait', '-nodesktop', '-noFigureWindows', '-sd', ('"' + $resolvedStartupDirectory + '"'),
        '-logfile', ('"' + $logPath + '"'), '-r', ('"' + $entryStatement + '"'))
    $matlabProcess = Start-Process -FilePath $MatlabPath -ArgumentList $arguments -WindowStyle Hidden -PassThru
    Write-Output "ADRC_MATLAB_STARTED pid=$($matlabProcess.Id) output=$runDirectory"
    $deadlineUtc = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    while (-not $matlabProcess.WaitForExit(1000)) {
        if ([DateTime]::UtcNow -ge $deadlineUtc) {
            throw "MATLAB timed out; inspect $logPath. Diagnostic process $($matlabProcess.Id) was left intact."
        }
    }
    $matlabProcess.Refresh()
    if (-not (Test-Path -LiteralPath $statusPath -PathType Leaf)) {
        throw "MATLAB exited before recording job status (exit $($matlabProcess.ExitCode)); inspect $logPath"
    }
    $jobStatus = Get-Content -LiteralPath $statusPath -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($matlabProcess.ExitCode -ne 0 -or -not $jobStatus.completed -or -not $jobStatus.success) {
        throw "MATLAB pipeline failed: $($jobStatus.error). Log: $logPath"
    }
    Write-Output "ADRC_MATLAB_PIPELINE_PASSED output=$runDirectory"
}

Invoke-AdrcMatlabPipeline
